name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        symfony-version: ['6.4.*', '7.0.*']
        include:
          - php-version: '8.1'
            symfony-version: '6.4.*'
            dependencies: 'lowest'
        exclude:
          - php-version: '8.1'
            symfony-version: '7.0.*'
          - php-version: '8.1'
            symfony-version: '6.4.*'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      - name: Configure Symfony Version
        run: |
          composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies || 'highest' }}

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run Tests
        run: vendor/bin/phpunit
